server:
  port: 10002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3360/wlhg?characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yd.taozi.pojo
myname: taozi-桃子xiaotaozi-111
